const fs = require('fs');
const path = require('path');

const publicDir = path.join(__dirname, '../public'); // public 目录
const headersFile = path.join(publicDir, '_headers');

// 生成 _headers 文件内容
let headersContent = `# Auto-generated by addHeaders.js

/docs/*
Content-Type: text/html; charset=utf-8
`;

// 写入 public/_headers
fs.writeFileSync(headersFile, headersContent, 'utf-8');
console.log('_headers 文件生成完成');

